spring:
  application:
    name: guangzhou-college
  datasource:
    url: jdbc:mysql://localhost:3306/guangzhou_college?useUnicode=true&characterEncoding=UTF8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    static-path-pattern: /image/**
  resources:
#    static-locations: file:/data/image/guangzhou_college_img
    static-locations: file:C:/guangzhou_college_img/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
server:
  port: 9331
  servlet:
    context-path: /guangzhou-college
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml

imageUrlPrefix: http://8.129.214.63:9331/guangzhou-college/image/ #https://www.eecup.cn/guangzhou-college/image/
imagePath: C:\guangzhou_college_img\ #/data/image/guangzhou_college_img/


wxConfig:
  wxspAppid: wx4123b4481a5e6e66
  grantType: authorization_code
  wxspSecret: bf861f60fbc30bf11ad07a73b4fbcf98
  mchId: 1540685681
  tradeType: JSAPI
  apiKey: eecup2019outlookcom1234567891234



# sql
# 打印sql
logging:
  level:
    com.guangzhou.college.dao: debug
